### ISSUE TITLE
README.md is not visible on NPM

### ISSUE THREAD

**Issue by BlueCutOfficial** [DazzlingFugu/ember-slugify#279]
With the migration to V2 addon, the `README.md` is no longer visible on NPM because we publish only the addon `dist`. The README.md should be visible on both GitHub and NPM page.

**Comment by MrChocolatine** [comment]
This will be fixed in #299 .

**Comment by MrChocolatine** [comment]
This will be fixed in #299 .

**Comment by MrChocolatine** [comment]
Double confirmation, the add-on's page on npm now shows the README:
https://www.npmjs.com/package/ember-slugify
