### ISSUE TITLE
Couldn't find package "@rollup/rollup-freebsd-arm64@4.24.1"

### ISSUE THREAD

**Issue by MrChocolatine** [DazzlingFugu/ember-slugify#419]
For context, see #418 .

Relates to https://github.com/rollup/rollup/issues/5704 .

**Comment by MrChocolatine** [comment]
Maybe a good sign to stop using `yarn` v1 (which is so old) and go back to `npm` like many projects did (or even `pnpm` since it seems to be the trend...).

**Comment by srinivasangurukannan** [comment]
> Maybe a good sign to stop using `yarn` v1 (which is so old) and go back to `npm` like many projects did (or even `pnpm` since it seems to be the trend...).

probably linux systems still prefer yarn v1

**Comment by MrChocolatine** [comment]
A fix is coming: https://github.com/rollup/rollup/pull/5705

**Comment by MrChocolatine** [comment]
Problem has been fixed:
- https://github.com/rollup/rollup/pull/5705

CI passes again on `master` and other branches:
- https://github.com/DazzlingFugu/ember-slugify/actions/runs/11539496516

I am closing this issue.
